### PR TITLE
Fixed #49

### LINKED ISSUE #49: atom.workspaceView is deprecated.
When I start Atom (0.174.0), I get the following warnings:

atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/atom.js:55:11)
Object.addListeners (/Users/victorhooi/.atom/packages/save-session/lib/project.coffee:34:9)
```

### PR DESCRIPTION
**Pull request by SalGnt**
See [Upgrading your package to 1.0 APIs](https://atom.io/docs/latest/upgrading/upgrading-your-package).

### CODE REVIEW

**Comment by mpeterson2** [comment]
Did this work for you? I have an issue with `projects.coffee`. The command `save-session:reopen-project` is not registered correctly. When I open the command palette it tells me:

```
Uncaught SyntaxError: Failed to execute 'webkitMatchesSelector' on 'Element': 'save-session:reopen-project' is not a valid selector.
```

I'm not really sure what's happening here. I've read the docs and tried to register it a few different ways, even exactly how it shows in the docs, yet it still won't work correctly.

**Comment by SalGnt** [comment]
I'm sorry, I made a mistake. This section
```coffee
atom.commands.add 'save-session:reopen-project', =>
      @onReopenProject()
```
should be
```coffee
atom.commands.add 'atom-workspace', 'save-session:reopen-project', =>
      @onReopenProject()
```

BTW I just noticed the following error in console.
```
'save-session.dataSaveFolder' could not set the default. Attempted default: undefined; Schema: {"type":"string","description":"The folder in which to save project states"}
```

**Comment by mpeterson2** [comment]
Okay cool. Thanks for contributing!

**Comment by SalGnt** [comment]
No problem, thank you for your work, this package is essential for me!

**Pull request merged**
