### PR TITLE
Multiple Root folders, deprecations, reduced HDD trafic by default

### PR DESCRIPTION
**Pull request by anthonyraymond**

### CODE REVIEW

**Comment by anthonyraymond** [comment]
All editors are now saved after one of them triggered : didStopChanged only.
If some were closed them atem is closed it wont be recorded and they will be opened again after restart. 
Havent find somefind line Atom::didDestroy to save when atom is closed.

**Comment by mpeterson2** [comment]
So does this mean that if you close a file, it will still have that file remembered until you edit another file?

So if we do this sequence:

  1. Open file `x` and file `y`
  2. Edit `x` and `y`
  2. Close `x`
  2. Close Atom
  2. Reopen Atom

File `x` will be reopened? But if we edit `y` after closing `x`, `x` would not be reopened? I would think that we would want to keep that functionality, unless they changed something so it is called when Atom is closed now?

Anyway, I took a quick look and it looks great so far. Just want to get a bit cleared up before merging since it's a large pull request.

**Comment by anthonyraymond** [comment]
@mpeterson2 Exactly, this is how it works.

I would have kept the close functionnality as well, but, when you close atom, all editors are closed one by one, so the last one to be opened overwrite the project.json.

I am thinking about a process to save each editor independently, because atm, when a save request is triggered, all editors are saved, even one which were not edited (causing useless HDD trafic and time loss), but i'm still at the reflexion phase.

**Comment by mpeterson2** [comment]
I've found a couple issues in here so far.

1. The issue that I mentioned above. I think it used to act like this before, and I caught an event (`window:beforeUnload`?) that fired just before Atom started closing. I would set a variable to `true` (or whatever) and then not save if that variable is `true`.
1. If I don't have a project open anymore, it seems to restore it from the last project open. This *should* be as simple as checking if Atom has a project path already.
2. It still opens the current project even when it is already open. Take a look at this [commit](https://github.com/mpeterson2/save-session/commit/bc1e4b7d0f205e58a04b45fafe7c9b0616cbd3d3).
2. The transform project method in config is never used anymore, which makes me think that this won't work on Windows anymore. That method basically gets rid of the `:` in the path so it is a valid path.

Besides these, it's looking good.

**Comment by anthonyraymond** [comment]
Hi,

1) Great, problem solved with my next commit thanks for the help.
2) Could you be more precise, i did not understand your request (how to reproduce)
3) Fixed
4) Yes, since the érester per project" ption was removed, it was useless to have a project.json stored in a specific folder reproducing the path of the file. Now, the project.json is stored in the save-session dataSaveFolder. I kept the method just in case. 
It is working in windows, im using Windows 7.


I added some improvement on file saving, i will merge branch to master soon, just waiting your answer for the second point.

**Comment by mpeterson2** [comment]
If I open a project, and then I want to open a new window, I would expect that window to be empty. However, with the change that you described in 4, all the files that are currently open in the first window will be reopened in the new window.

The same goes for opening a different folder. If I am working on Save Session, then want to open a different folder to work on a different project, all of the files I had open with Save Session would be opened with the new folder.

Then if you edit a file in the first project and don't save it, close the project and switch to the newly opened project, you will lose the changes you didn't save.

This is why I had the separation in there. It adds some complexity, but it makes it far more usable with multiple windows open.

**Comment by anthonyraymond** [comment]
With the last modifications, if you open a second widows it will be empty.

I understand what you did mean, but since we can have multiple projects in the same instance of atom, i don't think restoring by project will be a good idea.

example:
You open instance `A` of atom with folder `a` and folder `z` (a saved session)
You open instance `B` of atom with folder `b` (a saved session)

you work and then close both instances.

You want to restore instance `A` by opening folder `z`. If you do that, you won't have session `A` restored, cause session was saved in `a` save-folder.

Plus, if one month later you want to open folder `a` it will open `z` as well. And then you'll probably ask yourself what is this fuckery.


With my commits : 

You open instance `A` of atom with folder `a` and folder `z` (a saved session)
You open instance `B` of atom with folder `b` (a *non* saved session)

Close both instances.

whatever you do, on B and A, next time you will open atom, it will open session `A` with `a` and `b`.
Only the rist session is saved.





With the last commit i added save enchancement, reducing disk space used and disk trafic.

**Comment by mpeterson2** [comment]
I like all of the changes except for the one we're talking about. Would it be possible to revert that change so we can get the rest in? Then we can make an issue about it and see what other people might think is the best route to go? I just don't want the other good changes to have to wait until we decide on this and I don't really want to change how it functions before we've decided.

**Comment by anthonyraymond** [comment]
I understand this looks as a regression to you, but it would be way to long to revert changes since a commited my changed as a monkey. there is no way of cherry pick anything.

I'll understand if you would not like to include this pull request into your repo, but if you do not, feel free to include the changes y made by yourself ;)

My code is yours.

**Comment by mpeterson2** [comment]
Okay. No problem. I'll look into it later.

**Comment by mpeterson2** [comment]
Thanks for all the help. I was able to make the changes I wanted to your code and it is merged into version `0.13.0` now!

**Comment by anthonyraymond** [comment]
Great :)
Thanks for the merge and for the reference in the Changelog.

**Comment by anthonyraymond** [comment]
By the way, the problem on file saving on exist should be that, we use to write to the file in a callback.
It might be concurrence problem when file is writen by two or more callback at the same time. (i believe it was fixed by saving with : `window.onbeforeunload` (since it should be callend only once), but it might have not.

Since it is called with a callback `Fs.writeFileSync` wont help. I encountered the problem while testing save on close.

**Comment by mpeterson2** [comment]
Yeah I think the `window.onbeforeunload` will work. I'm just not sure how event catching works in Atom anymore to try it out again.

**Pull request merged**
